# yaml-language-server: $schema=./monitor.schema.json

resourceGroup:
  name: apim-monitoring-rg

logAnalytics:
  name: "apim-accelerator-law"
  provisionStorageAccount: true

applicationInsights:
  enabled: true
  name: "apim-accelerator-ai"