name: apimVirtualNetwork
description: Configuration settings for the network infrastructure including VNet, subnets, Azure Bastion, Azure Firewall, and DDoS protection.

ipAddresses:
  addressSpaces:
    - 10.0.0.0/16
  subnets:
    privateEndpoint:
      name: privateEndPointSubnet
      addressPrefix: 10.0.1.0/24
      networkSecurityGroup:
        name: privateEndpointNsg
    apiManagement:
      name: apiManagementSubnet
      addressPrefix: 10.0.2.0/24
      networkSecurityGroup:
        name: apimApiManagementNSG
    applicationGateway:
      name: appGatewaySubnet
      addressPrefix: 10.0.3.0/24
      networkSecurityGroup:
        name: apimAppGatewayNSG

diagnostics:
  enabled: true

security:
  encryption:
    enabled: true
  azureFirewall:
    enabled: true
    name: apimFirewall
  ddosProtection:
    enabled: true
    name: apimDdosPlan
