name: apim-virtual-network
description: Configuration settings for the network infrastructure including VNet, subnets, Azure Bastion, Azure Firewall, and DDoS protection.

resourceGroup:
  name: apim-network-rg

ipAddresses:
  addressSpaces: 
    - 10.0.0.0/16
  subnets:
    - name: AzureBastionSubnet
      addressPrefix: 10.0.1.0/24
    - name: AzureFirewallSubnet
      addressPrefix: 10.0.2.0/24

security:
  encryption:
    enabled: true
  azureBastion:
    enabled: true
    name: myBastion
    hostName: myBastionHost
    publicIPAddressName: myBastionPublicIP
    subnetName: AzureBastionSubnet
  azureFirewall:
    enabled: true
    name: myAzureFirewall
    subnetName: AzureFirewallSubnet
    Tier: Standard
    policy: myFirewallPolicy
    publicIPAddressName: myFirewallPublicIP
  ddosProtection:
    enabled: true
    planName: myDDoSPlan